### ISSUE TITLE
Better way to indicate that this repo is deprecated

### ISSUE THREAD

**Issue by JacksonBurns** [atomistic-machine-learning/G-SchNet#10]
You may want to set this repository as a Public Archive, see [the GitHub documentation](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories). This would really emphasize the point you make in the README about using the updated implementation.

**Comment by NiklasGebauer** [comment]
Hi @JacksonBurns,

thank you for the suggestion, I didn't know about this feature!
I'm a bit reluctant to archiving the repo at the moment as it is still relevant for reproduction of our published results. I would like to provide support as long as time permits in case somebody has trouble reproducing our results and as far as I understand setting the repository as a Public Achive would also freeze the issues. Also, I need to update the readme once in a while, e.g. to update installation instructions if packages become unavailable via conda (which happened lately and caused the code to always run on the cpu instead of the gpu).

However, I will keep this in mind for the future as there will definitely come a time where I cannot maintain the repo anymore.

Thanks and regards,
Niklas
