### ISSUE TITLE
Issues about using custom dataset

### ISSUE THREAD

**Issue by Layne-Huang** [atomistic-machine-learning/G-SchNet#7]
Hi,

I found that you have provided the code for the custom dataset. However, the "template_data.py" requires db_name as input. What should I do to prepare for the db file since my raw data is another type? 

Thank you very much!

Best regards,
Lei

**Comment by NiklasGebauer** [comment]
Hi,

in order to use `template_data.py` you need to convert your raw data into an [ASE SQLite3](https://wiki.fysik.dtu.dk/ase/ase/db/db.html) data base.

The ASE package can handle and convert data of molecular structures in different file formats ([see here](https://wiki.fysik.dtu.dk/ase/ase/io/io.html)). You can probably use `ase.io.read` to read your raw data and then write it to the required `.db` file with `ase.db.connect`. For example, lets assume you have 1000 structures in individual `.xyz` files. Then you can do something similar to:

```
from ase.io import read
from ase.db import connect

with connect("./template_data.db") as target:  # connect to target .db file
    for i in range(1000):
        data = read(f"./{i}.xyz", format="xyz")  # read molecule from raw data
        target.write(data)  # write molecule to data base
```
Afterwards, you can use the resulting `.db` file with `template_data.py`. You only need to specify a few hyper-parameters at the top of the file (e.g. the atom types in the data set, the minimum and maximum distance between atoms you consider to be neighbors) as described [here](https://github.com/atomistic-machine-learning/G-SchNet#adjusting-the-template-data-class).

Hope this helps!
Best,
Niklas
